# Generated by Django 2.2 on 2019-04-13 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('elo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(related_name='teams', to='foos.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_score', models.IntegerField()),
                ('losing_score', models.IntegerField()),
                ('losing_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losing_matches', to='foos.Team')),
                ('winning_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winning_matches', to='foos.Team')),
            ],
        ),
    ]
